wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.2
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718977563
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.11.9
      5: 0.17.2
      8:
      - 1
      - 4
      - 5
      10:
      - 9
      13: darwin-arm64
learning_rate:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: adam
